user: user code {
    near: top-left
    entity1: e1 (Entity): \{ id: 0, gen: 0 \}
    entity2: e2 (Entity): \{ id: 0, gen: 0 \}
    
    entity1 -> entity2 { style.opacity: 0 }
}

world: {
    near: top-right
    api: {
        createEntity: createEntity(Entity)
        deleteEntity: deleteEntity(Entity)
    }

    entities: {
        grid-rows: 2
        grid-columns: 6
        grid-gap: 0

        1-0: entityId
        1-1: x
        1-2: x
        1-3: x
        1-4: x
        1-5: x

        2-0: gen
        2-1: 0
        2-2: 0
        2-3: 0
        2-4: 0
        2-5: 0
    }

    api.createEntity -> api.deleteEntity { style.opacity: 0 }
}

scenarios: {
    1: {
        user.entity1: e1 (Entity): \{ id: 0, gen: 0 \} { style.stroke: red }
        user.entity2: e2 (Entity): \{ id: 0, gen: 0 \} { style.stroke: red }
        user -> world.api.createEntity { style.animated: true }
    }
    2: {
        world.entities.1-1: 1 { style.fill: green }
        user.entity1: e1 (Entity): \{ id: 0, gen: 0 \} { style.stroke: red }
        user.entity2: e2 (Entity): \{ id: 0, gen: 0 \} { style.stroke: red }
        world.api.createEntity -> world.entities.1-1 { style.animated: true }
    }
    3: {
        world.entities.1-1: 1
        user.entity1: e1 (Entity): \{ id: 0, gen: 0 \} { style.stroke: red }
        user.entity2: e2 (Entity): \{ id: 0, gen: 0 \} { style.stroke: red }
        world.api.createEntity <- world.entities.1-1 { style.animated: true }
    }
    4: {
        world.entities.1-1: 1
        user.entity1: e1 (Entity): \{ id: 1, gen: 0 \} 
        user.entity2: e2 (Entity): \{ id: 0, gen: 0 \} { style.stroke: red }
        world.api.createEntity -> user.entity1 { style.animated: true }
    }
    5: {
        world.entities.1-1: 1
        user.entity1: e1 (Entity): \{ id: 1, gen: 0 \} 
        user.entity2: e2 (Entity): \{ id: 0, gen: 0 \} { style.stroke: red }
        user -> world.api.createEntity { style.animated: true }
    }
    6: {
        world.entities.1-1: 1
        world.entities.1-2: 1 { style.fill: green }
        user.entity1: e1 (Entity): \{ id: 1, gen: 0 \} 
        user.entity2: e2 (Entity): \{ id: 0, gen: 0 \} { style.stroke: red }
        world.api.createEntity -> world.entities.1-2 { style.animated: true }
    }
    7: {
        world.entities.1-1: 1
        world.entities.1-2: 1
        user.entity1: e1 (Entity): \{ id: 1, gen: 0 \} 
        user.entity2: e2 (Entity): \{ id: 0, gen: 0 \} { style.stroke: red }
        world.api.createEntity <- world.entities.1-2 { style.animated: true }
    }
    8: {
        world.entities.1-1: 1
        world.entities.1-2: 1
        user.entity1: e1 (Entity): \{ id: 1, gen: 0 \} 
        user.entity2: e2 (Entity): \{ id: 2, gen: 0 \}
        world.api.createEntity -> user.entity2 { style.animated: true }
    }
    9: {
        world.entities.1-1: 1
        world.entities.1-2: 1
        user.entity1: e1 (Entity): \{ id: 1, gen: 0 \}
        user.entity2: e1 (Entity): \{ id: 2, gen: 0 \}
        user.entity1 -> world.api.deleteEntity { style.animated: true }
    }
    10: {
        world.entities.1-1: 1
        world.entities.1-2: 1
        world.entities.2-1: 1 { style.fill: green }
        user.entity1: e1 (Entity): \{ id: 1, gen: 0 \} { style.stroke: red }
        user.entity2: e2 (Entity): \{ id: 2, gen: 0 \}
        world.api.deleteEntity -> world.entities.2-1 { style.animated: true }
    }
    11: {
        world.entities.1-1: 1
        world.entities.1-2: 1
        world.entities.2-1: 1
        user.entity1: e1 (Entity): \{ id: 1, gen: 0 \} { style.stroke: red }
        user.entity2: e1 (Entity): \{ id: 2, gen: 0 \}
        user.entity2 -> world.api.deleteEntity { style.animated: true }
    }
    12: {
        world.entities.1-1: 1
        world.entities.1-2: 1
        world.entities.2-1: 1
        world.entities.2-2: 1 { style.fill: green }
        user.entity1: e1 (Entity): \{ id: 1, gen: 0 \} { style.stroke: red }
        user.entity2: e2 (Entity): \{ id: 2, gen: 0 \} { style.stroke: red }
        world.api.deleteEntity -> world.entities.2-2 { style.animated: true }
    }
}