classes: {
  none: { style.opacity: 0}
  arrow: {
      style.stroke: "#ffffff"
  }
  s1: { style.fill: "#2b9464" }
  s2: { style.fill: "#b14d28" }
  s3: { style.fill: "#29678f" }
  s4: { style.fill: "#a9678f" }
  s5: { style.fill: "#49672f" }
  s6: { style.fill: "#79278f" }
  s7: { style.fill: "#99272f" }
  s8: { style.fill: "#29678f" }
  s9: { style.fill: "#696969" }
}

grid-rows: 4
grid-columns: 4
grid-gap: 0

1-1: ""
1-2: E1
1-3: E2
1-4: E3

2-1: T1
2-2: c1 {class: s1}
2-3: c1 {class: s1}
2-4: c1 {class: s1}

3-1: T2
3-2: c2 {class: s2}
3-3: c2 {class: s2}
3-4: c2 {class: s2}

4-1: T3
4-2: c3 {class: s3}
4-3: c3 {class: s3}
4-4: c3 {class: s3}