classes: {
    none: { style.opacity: 0}
    arrow: {
        style.border-radius: 20
        style.stroke: "#ffffff"
    }
    s1: { style.fill: "#2b9464" }
    s2: { style.fill: "#b14d28" }
    s3: { style.fill: "#29678f" }
    s4: { style.fill: "#a9678f" }
    s5: { style.fill: "#49672f" }
    s6: { style.fill: "#79278f" }
    s7: { style.fill: "#99272f" }
    s8: { style.fill: "#29678f" }
    s9: { style.fill: "#696969" }
}

world-1: {
    archetypes (number): {
        grid-rows: 2
        grid-columns: 11
        grid-gap: 0

        1: 1
        2: 2
        3: 3
        4: 4
        5: 5
        6: 6
        7: 7
        8: 8
        9: 9
        10: 10
        11: 11

        _1: 1
        _2: 1
        _3: 2
        _4: 3
        _5: 3
        _6: 3
        _7: 4
        _8: 4
        _9: 5
        _10: 4
        _11: 4
    }

    archetype-1: {
        grid-rows: 4
        grid-columns: 3
        grid-gap: 0
        
        1-1: entityId
        1-2: 1
        1-3: 2

        2-1: component 2
        2-2: c2 {class: s2}
        2-3: c2 {class: s2}

        3-1: component 3
        3-2: c3 {class: s3}
        3-3: c3 {class: s3}

        4-1: component 6
        4-2: c6 {class: s6}
        4-3: c6 {class: s6}
    }
    archetype-2: {
        grid-rows: 2
        grid-columns: 2
        grid-gap: 0

        1-1: entityId
        1-2: 3

        2-1: component 9
        2-2: c9 {class: s9}
    }
    archetype-3: {
        grid-rows: 4
        grid-columns: 4
        grid-gap: 0
        
        1-1: entityId
        1-2: 4
        1-3: 5
        1-4: 6

        2-1: component 1
        2-2: c1 {class: s1}
        2-3: c1 {class: s1}
        2-4: c1 {class: s1}

        3-1: component 2
        3-2: c2 {class: s2}
        3-3: c2 {class: s2}
        3-4: c2 {class: s2}

        4-1: component 3
        4-2: c3 {class: s3}
        4-3: c3 {class: s3}
        4-4: c3 {class: s3}
    }
    archetype-4: {
        grid-rows: 6
        grid-columns: 5
        grid-gap: 0
        
        1-1: entityId
        1-2: 7
        1-3: 8
        1-4: 10
        1-5: 11

        2-1: component 1
        2-2: c1 {class: s1}
        2-3: c1 {class: s1}
        2-4: c1 {class: s1}
        2-5: c1 {class: s1}

        3-1: component 3
        3-2: c3 {class: s3}
        3-3: c3 {class: s3}
        3-4: c3 {class: s3}
        3-5: c3 {class: s3}

        4-1: component 4
        4-2: c4 {class: s4}
        4-3: c4 {class: s4}
        4-4: c4 {class: s4}
        4-5: c4 {class: s4}

        5-1: component 6
        5-2: c6 {class: s6}
        5-3: c6 {class: s6}
        5-4: c6 {class: s6}
        5-5: c6 {class: s6}
    }
    archetype-5: {
        grid-rows: 2
        grid-columns: 2
        grid-gap: 0

        1-1: entityId
        1-2: 9

        2-1: component 8
        2-2: c8 {class: s8}
    }

    archetypes (number) -> archetype-1 { style.opacity: 0 }
    archetypes (number) -> archetype-3 { style.opacity: 0 }
    archetype-1 -> archetype-4 { style.opacity: 0 }
    archetype-3 -> archetype-4 { style.opacity: 0 }
    archetype-4 -> archetype-2 { style.opacity: 0 }
    archetype-4 -> archetype-5 { style.opacity: 0 }
}

world-2: {
    archetypes (number): {
        grid-rows: 2
        grid-columns: 11
        grid-gap: 0

        1: 1
        2: 2
        3: 3
        4: 4
        5: 5
        6: 6
        7: 7
        8: 8
        9: 9
        10: 10
        11: 11

        _1: 1
        _2: 1
        _3: 2
        _4: 3
        _5: 3
        _6: 3
        _7: 4
        _8: 4
        _9: 5
        _10: 4
        _11: 4
    }

    archetype-1: {
        grid-rows: 1
        grid-columns: 2
        grid-gap: 0
        
        entity 1:  {
            grid-rows: 1
            grid-columns: 3
            grid-gap: 0 

            1: c2 {class: s2}
            2: c3 {class: s3}
            3: c6 {class: s6}
        }

        entity 2:  {
            grid-rows: 1
            grid-columns: 3
            grid-gap: 0 

            1: c2 {class: s2}
            2: c3 {class: s3}
            3: c6 {class: s6}
        }
    }
    archetype-2: {
        grid-rows: 1
        grid-columns: 1
        grid-gap: 0

        entity 3:  {
            grid-rows: 1
            grid-columns: 3
            grid-gap: 0 

            1: c9 {class: s9}
        }
    }

    archetype-3: {
        grid-rows: 1
        grid-columns: 3
        grid-gap: 0
        
        entity 4:  {
            grid-rows: 1
            grid-columns: 3
            grid-gap: 0 

            1: c1 {class: s1}
            2: c2 {class: s2}
            3: c3 {class: s3}
        }

        entity 5:  {
            grid-rows: 1
            grid-columns: 3
            grid-gap: 0 

            1: c1 {class: s1}
            2: c2 {class: s2}
            3: c3 {class: s3}
        }

        entity 6:  {
            grid-rows: 1
            grid-columns: 3
            grid-gap: 0 

            1: c1 {class: s1}
            2: c2 {class: s2}
            3: c3 {class: s3}
        }
    }
    archetype-4: {
        grid-rows: 2
        grid-columns: 2
        grid-gap: 0
        
        entity 7:  {
            grid-rows: 1
            grid-columns: 4
            grid-gap: 0 

            1: c1 {class: s1}
            2: c3 {class: s3}
            3: c4 {class: s4}
            4: c6 {class: s6}
        }

        entity 8:  {
            grid-rows: 1
            grid-columns: 4
            grid-gap: 0 

            1: c1 {class: s1}
            2: c3 {class: s3}
            3: c4 {class: s4}
            4: c6 {class: s6}
        }

        entity 10:  {
            grid-rows: 1
            grid-columns: 4
            grid-gap: 0 

            1: c1 {class: s1}
            2: c3 {class: s3}
            3: c4 {class: s4}
            4: c6 {class: s6}
        }

        entity 11:  {
            grid-rows: 1
            grid-columns: 4
            grid-gap: 0 

            1: c1 {class: s1}
            2: c3 {class: s3}
            3: c4 {class: s4}
            4: c6 {class: s6}
        }
    }
    archetype-5: {
        grid-rows: 1
        grid-columns: 1
        grid-gap: 0

        entity 9:  {
            grid-rows: 1
            grid-columns: 3
            grid-gap: 0 

            1: c8 {class: s8}
        }
    }

    archetypes (number) -> archetype-1 { style.opacity: 0 }
    archetype-1 -> archetype-2 { style.opacity: 0 }
    archetype-1 -> archetype-5 { style.opacity: 0 }
    archetype-2 -> archetype-3 { style.opacity: 0 }
    archetype-5 -> archetype-3 { style.opacity: 0 }
    archetype-3 -> archetype-4 { style.opacity: 0 }
}